apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvn-stack.clientName" . }}
spec:
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: 80
  selector:
    app: {{ include "mvn-stack.clientName" . }}
  type: NodePort
