{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mvn-stack.fullname" . }}-ingress
  metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mvn-stack.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mvn-stack.frontendFullname" . }}
                port:
                  number: {{ .Values.client.service.port }}
{{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
{{- end }}
