{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvn-stack.mysqlFullname" . }}
  labels:
    {{- include "mvn-stack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "mvn-stack.name" . }}
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
{{- end }}
