{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvn-stack.mysqlSecretName" . }}
  metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mvn-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mysql.user }}
  password: {{ .Values.mysql.password }}
{{- end }}
