apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvn-stack.mysqlFullname" . }}-mysql
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  selector:
    app: {{ include "mvn-stack.mysqlFullname" . }}-mysql
