apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mvn-stack.backendFullname" . }}
  metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mvn-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mvn-stack.name" . }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mvn-stack.name" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy | default .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://{{ include "mvn-stack.mysqlFullname" . }}:3306/{{ .Values.mysql.database }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mvn-stack.mysqlSecretName" . }}
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mvn-stack.mysqlSecretName" . }}
                  key: password
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
